/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;

import java.awt.Dimension;
import javax.swing.JFrame;
import proyectopoodefinitivo.Partido;

/**
 *
 * @author Yeison
 */
public class Menu extends javax.swing.JFrame {

    Creditos cre = new Creditos();
    private boolean musica;
    private Dimension dim;

    public Menu(boolean musica) {
        initComponents();
        dim = super.getToolkit().getScreenSize();
        super.setSize(dim);
        setResizable(false);
        this.musica = musica;
        if (this.musica) {
            music();
        }
    }

    public void music() {
        Thread sonido = new Thread(new ReproducirSonido());
        sonido.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        ControlesDeJuego = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        Creditos = new javax.swing.JButton();
        Partido = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1350, 700));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menu1.png"))); // NOI18N
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(440, -10, 470, 119);

        ControlesDeJuego.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Controles copia.png"))); // NOI18N
        ControlesDeJuego.setBorderPainted(false);
        ControlesDeJuego.setContentAreaFilled(false);
        ControlesDeJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ControlesDeJuegoActionPerformed(evt);
            }
        });
        getContentPane().add(ControlesDeJuego);
        ControlesDeJuego.setBounds(360, 400, 650, 100);

        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Salir copia.png"))); // NOI18N
        Salir.setBorderPainted(false);
        Salir.setContentAreaFilled(false);
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir);
        Salir.setBounds(570, 590, 230, 90);

        Creditos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Creditos copia.png"))); // NOI18N
        Creditos.setBorderPainted(false);
        Creditos.setContentAreaFilled(false);
        Creditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreditosActionPerformed(evt);
            }
        });
        getContentPane().add(Creditos);
        Creditos.setBounds(540, 500, 290, 90);

        Partido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/partido copia.png"))); // NOI18N
        Partido.setBorderPainted(false);
        Partido.setContentAreaFilled(false);
        Partido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PartidoActionPerformed(evt);
            }
        });
        getContentPane().add(Partido);
        Partido.setBounds(550, 310, 260, 100);

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/james3.jpg"))); // NOI18N
        Fondo.setMaximumSize(new java.awt.Dimension(1405, 773));
        Fondo.setMinimumSize(new java.awt.Dimension(1405, 773));
        getContentPane().add(Fondo);
        Fondo.setBounds(0, 0, 1350, 750);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void CreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreditosActionPerformed
        // TODO add your handling code here:
//        interrumpirMusica();
        Creditos creditos = new Creditos();
        creditos.setVisible(true);
        dispose();
    }//GEN-LAST:event_CreditosActionPerformed

    private void PartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PartidoActionPerformed
        // TODO add your handling code here:

        JFrame Frame = new JFrame("Fifa20");
        Partido cotejo = new Partido();
        Frame.add(cotejo);

        Frame.setSize(1033, 730);
        Frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        Frame.setResizable(false);
        Frame.setLocationRelativeTo(null);
        Frame.setVisible(true);
        Frame.setLayout(null);
        dispose();
    }//GEN-LAST:event_PartidoActionPerformed

    private void ControlesDeJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ControlesDeJuegoActionPerformed
        // TODO add your handling code here:
        ControlesJuego controles = new ControlesJuego();
        controles.setVisible(true);
        dispose();
    }//GEN-LAST:event_ControlesDeJuegoActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu(true).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ControlesDeJuego;
    private javax.swing.JButton Creditos;
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton Partido;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
